---
- hosts: all
  become: yes
  gather_facts: yes
  vars:
    - haka_url: "http://github.com/haka-security/haka/releases/download"
    - haka_ver: "0.3.0"
    - haka_file: "haka_{{ haka_ver }}_amd64.deb"
    - nfqueue_ver: "0.3.0"
    - nfqueue_file: "haka-nfqueue_{{ nfqueue_ver }}_amd64.deb"
    - haka_path: "/etc/haka"
    - git_user_name: "nechinechi"
    - git_user_email: "s13t245@stmail.eng.kagawa-u.ac.jp"
  tasks:
    - name: apt-get update
      apt: update_cache=yes
    - apt: name="apache2" state=latest
    - service: name="apache2" state=restarted
    - template: src=../playbooks/index.html.j2 dest=/var/www/html/index.html
    - include: ../playbooks/ssh_key.yml
    - include: ../playbooks/git.yml
    - include: ../playbooks/haka.yml
